- hosts: localhost
  connection: local
  tasks:
  - name: Create a service
    community.kubernetes.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: petclinic-svc
          namespace: default
          labels:
            app: petclinic
        spec:
          selector:
            app: petclinic
          type: NodePort
          ports:
          - nodePort: 31000
            targetPort: 8080
            port: 8080
        
  - name: Create a Deployment
    community.kubernetes.k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: petclinic
          namespace: default
          labels:
            app: petclinic
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: petclinic
          template:
            metadata:
              labels:
                app: petclinic
            spec:
              containers:
              - name: petclinic
                image: '{{ image }}'
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: 8080